# This is a config for E2B sandbox template.
# You can use template ID (tlahv91cck2pgvg72m7v) or template name (vibe-nextjs-temp-test-303) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-temp-test-303") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-temp-test-303") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-temp-test-303')

team_id = "9ef59663-7a90-4a7e-a1f4-e0f09c0cae3a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-temp-test-303"
template_id = "tlahv91cck2pgvg72m7v"
